### PR TITLE
removing unused namespaces

### PR DESCRIPTION
**Pull request by MovGP0**
removing unused namespaces in order to speed up the compiler and static code analyzers

### CODE REVIEW

**Comment by MovGP0** [comment]
tests are also failing in original master branch. errors not introduced here.

**Comment by Oceania2018** [comment]
Johann, are you sure it will speed up the compiler ?

**Comment by MovGP0** [comment]
> Johann, are you sure it will speed up the compiler ?

yes, but usually you wont't notice except in benchmarking. also the autocomplete is cleaner with fewer imports.

**Comment by MovGP0** [comment]
also implemented explicit and implicit type conversion from scalars to tensors and tensors to scalars.

**Pull request merged**
