### PR TITLE
refactor: python test common class moved to a separate common assembly

### PR DESCRIPTION
**Pull request by novikov-alexander**

### CODE REVIEW

**Comment by novikov-alexander** [comment]
@AsakusaRinne in this project nullable is enabled by default. I can change if needed.

**Comment by novikov-alexander** [comment]
@AsakusaRinne I can convert it to fsproj if needed to force users use F# in tests. However, I think it doesn't make sense for a class.

**Comment by novikov-alexander** [comment]
@AsakusaRinne how to get value of Ndarray if an Ndarray is a scalar?

**Comment by Oceania2018** [comment]
> @AsakusaRinne how to get value of Ndarray if an Ndarray is a scalar?

You can just use `int a = nd;` for implication converting.

**Comment by Oceania2018** [comment]
```shell
  Error Message:
   Test method TensorFlowNET.UnitTest.Gradient.GradientTest.testDependentYs threw exception: 
System.NotImplementedException: 
  Stack Trace:
      at Tensorflow.NumPy.np.allclose(NDArray a, NDArray b, Double rtol, Double atol, Boolean equal_nan) in /home/runner/work/TensorFlow.NET/TensorFlow.NET/src/TensorFlowNET.Core/Numpy/Numpy.cs:line 69
   at TensorFlowNET.UnitTest.PythonTest.assertAllClose(Double value, NDArray array2, Double eps) in /home/runner/work/TensorFlow.NET/TensorFlow.NET/test/Tensorflow.UnitTest/PythonTest.cs:line 142
   at TensorFlowNET.UnitTest.Gradient.GradientTest.testDependentYs() in /home/runner/work/TensorFlow.NET/TensorFlow.NET/test/TensorFlowNET.Graph.UnitTest/GradientTest/GradientTest.cs:line 600
```

**Comment by novikov-alexander** [comment]
> ```shell
>   Error Message:
>    Test method TensorFlowNET.UnitTest.Gradient.GradientTest.testDependentYs threw exception: 
> System.NotImplementedException: 
>   Stack Trace:
>       at Tensorflow.NumPy.np.allclose(NDArray a, NDArray b, Double rtol, Double atol, Boolean equal_nan) in /home/runner/work/TensorFlow.NET/TensorFlow.NET/src/TensorFlowNET.Core/Numpy/Numpy.cs:line 69
>    at TensorFlowNET.UnitTest.PythonTest.assertAllClose(Double value, NDArray array2, Double eps) in /home/runner/work/TensorFlow.NET/TensorFlow.NET/test/Tensorflow.UnitTest/PythonTest.cs:line 142
>    at TensorFlowNET.UnitTest.Gradient.GradientTest.testDependentYs() in /home/runner/work/TensorFlow.NET/TensorFlow.NET/test/TensorFlowNET.Graph.UnitTest/GradientTest/GradientTest.cs:line 600
> ```

Yes, one of the tests wasn't fully enabled info (in one of my previous PRs). Now the assertion works correctly and the error above is fixed.

**Comment by novikov-alexander** [comment]
> > @AsakusaRinne how to get value of Ndarray if an Ndarray is a scalar?
> 
> You can just use `int a = nd;` for implication converting.

Thank you!

**Pull request merged**
