### PR TITLE
Tf redist migration

### PR DESCRIPTION
**Pull request by harishsk**
Migrated the project that packages tensorflow binaries into a nuget package from the ML.NET repo to the TensorFlow.NET repo.

### CODE REVIEW

**Comment by Oceania2018** [comment]
When I run `dotnet pack` on Ubuntu:

```shell
haiping@haiping-Latitude-E5470:~/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist$ dotnet pack
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 24.23 ms for /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/SciSharp.TensorFlow.Redist.nupkgproj.
  win-x64
  linux-x64
  osx-x64
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-windows-x86_64-1.14.0/lib/tensorflow.dll -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/runtimes/win-x64/native/tensorflow.dll
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-windows-x86_64-1.14.0/include/tensorflow/c/LICENSE;/home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-linux-x86_64-1.14.0.tar/include/tensorflow/c/LICENSE;/home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-darwin-x86_64-1.14.0.tar/include/tensorflow/c/LICENSE -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/THIRD_PARTY_NOTICES.txt
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-linux-x86_64-1.14.0.tar/lib/libtensorflow.so -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/runtimes/linux-x64/native/libtensorflow.so
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-linux-x86_64-1.14.0.tar/lib/libtensorflow_framework.so.1 -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/runtimes/linux-x64/native/libtensorflow_framework.so.1
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-darwin-x86_64-1.14.0.tar/lib/libtensorflow.dylib -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/runtimes/osx-x64/native/libtensorflow.dylib
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/libtensorflow-cpu-darwin-x86_64-1.14.0.tar/lib/libtensorflow_framework.1.dylib -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/runtimes/osx-x64/native/libtensorflow_framework.1.dylib
  /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/LICENSE -> /home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/bin/packages/SciSharp.TensorFlow.Redist/LICENSE.txt
/usr/share/dotnet/sdk/2.2.301/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(199,5): error NU5008: Manifest file not found at '/home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/Redist.nuspec' [/home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/SciSharp.TensorFlow.Redist.nupkgproj]
```

**Comment by Oceania2018** [comment]
@harishsk Run It On Windows. Only pack for windows:

```cmd
PS D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist> dotnet pack
Microsoft (R) Build Engine version 16.0.462+g62fb89029d for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 143.3 ms for D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\SciSharp.TensorFlow.Redist.nupkgproj.
  win-x64
  Downloading 'https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.14.0.zip' to 'D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\'.
  Downloading 'https://raw.githubusercontent.com/tensorflow/tensorflow/master/LICENSE' to 'D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\'.
  Downloading from "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.14.0.zip" to "D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0.zip" (26,933,591 bytes).
  Downloading from "https://raw.githubusercontent.com/tensorflow/tensorflow/master/LICENSE" to "D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\LICENSE" (11,419 bytes).
  D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0.zip: 59A2B80B441439B851202358CE4A65BA0DDDB319A8A29E87B135DCD9954BC5B0628F2C0C8E72D6942EA3CDCE172805C2BD5421815B3D0210B62BC0936DC59A08
  @TensorFlowArchive->'D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0.zip - 59A2B80B441439B851202358CE4A65BA0DDDB319A8A29E87B135DCD9954BC5B0628F2C0C8E72D6942EA3CDCE172805C2BD5421815B3D0210B62BC0936DC59A08 - 59A2B80B441439B851202358CE4A65BA0DDDB319A8A29E87B135DCD9954BC5B0628F2C0C8E72D6942EA3CDCE172805C2BD5421815B3D0210B62BC0936DC59A08
  Decompressing 'D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0.zip' to 'D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0'.
  D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0\lib\tensorflow.dll -> D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\packages\SciSharp.TensorFlow.Redist\runtimes\win-x64\native\tensorflow.dll
  D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\libtensorflow-cpu-windows-x86_64-1.14.0\include\tensorflow\c\LICENSE -> D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\packages\SciSharp.TensorFlow.Redist\THIRD_PARTY_NOTICES.txt
  D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\\LICENSE -> D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\packages\SciSharp.TensorFlow.Redist\LICENSE.txt
  Successfully created package 'D:\SciSharp\TensorFlow.NET\src\SciSharp.TensorFlow.Redist\bin\Debug\SciSharp.TensorFlow.Redist.1.14.0.nupkg'.
```
image

**Comment by harishsk** [comment]
On Windows, the tar command does not support extracting archives with symlinks. So when dotnet pack is run on Windows it will only package the Windows binaries. 

I am not seeing the error you see on Ubuntu. Can you please run the following command and mail me the log file:

dotnet pack -v diag > pack.log 2>&1

**Comment by Oceania2018** [comment]
`NuGet.Packaging.Core.PackagingException: Manifest file not found at '/home/haiping/Projects/TensorFlow.NET/src/SciSharp.TensorFlow.Redist/Redist.nuspec'`

[pack.log](https://github.com/SciSharp/TensorFlow.NET/files/3388280/pack.log)

**Pull request merged**
